package com.example.searchengine.infrastructure.metrics;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.boot.test.context.SpringBootTest.WebEnvironment.RANDOM_PORT;

/**
 * Integration test for the Prometheus actuator scrape endpoint.
 *
 * <p>Validates Requirements 1.1, 1.2 (operability quick-wins): the application
 * exposes {@code /actuator/prometheus} with HTTP 200 and the Prometheus
 * exposition format {@code text/plain; version=0.0.4} content type, populated
 * with the Spring Boot baseline meters.</p>
 *
 * <p>Boots the full Spring Boot context with a randomly-bound port and a real
 * PostgreSQL 16 instance via Testcontainers. The Spring context is configured
 * via {@link DynamicPropertySource} to:
 * <ul>
 *   <li>point the datasource at the running PostgreSQL container,</li>
 *   <li>satisfy the required configuration properties enforced by
 *       {@code ConfigValidator} (provider base URLs are stubbed),</li>
 *   <li>disable the background sync scheduler so tests run deterministically,</li>
 *   <li>disable the rate limiter (irrelevant here, keeps the boot path
 *       simple — no Redis dependency for buckets either),</li>
 *   <li>disable search caching so the boot path needs no live Redis.</li>
 * </ul>
 * </p>
 */
@SpringBootTest(webEnvironment = RANDOM_PORT)
@Testcontainers
class PrometheusEndpointIT {

    @Container
    static final PostgreSQLContainer<?> POSTGRES =
            new PostgreSQLContainer<>("postgres:16")
                    .withDatabaseName("searchengine_test")
                    .withUsername("test")
                    .withPassword("test");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
        // Stub provider base-urls so config validation passes; no provider HTTP
        // traffic is generated by /actuator/prometheus.
        registry.add("providers.json.base-url", () -> "http://localhost:0/json");
        registry.add("providers.xml.base-url", () -> "http://localhost:0/xml");
        // Disable scheduled sync so the aggregator never tries to reach the
        // stubbed providers during the test run.
        registry.add("aggregator.sync.enabled", () -> "false");
        // Disable rate limiting (path-irrelevant for /actuator/prometheus but
        // keeps the boot path simple — no Redis dependency for buckets).
        registry.add("ratelimit.enabled", () -> "false");
        // Disable Redis-backed caching; @Cacheable becomes a no-op via
        // NoOpCacheManager so the suite has no Redis dependency.
        registry.add("cache.search.enabled", () -> "false");
    }

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    @DisplayName("GET /actuator/prometheus returns 200 with the Prometheus 0.0.4 exposition format")
    void prometheusEndpointReturns200WithExpositionContentType() {
        ResponseEntity<String> response = restTemplate.getForEntity(
                "http://localhost:" + port + "/actuator/prometheus",
                String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);

        // Spring Boot exposes Prometheus scrape data with Content-Type
        // "text/plain; version=0.0.4;charset=utf-8" (the exact charset
        // segment may vary). Assert the two stable parts.
        String contentType = response.getHeaders().getFirst("Content-Type");
        assertThat(contentType)
                .as("Prometheus scrape endpoint must return a text/plain response")
                .isNotNull()
                .startsWith("text/plain");
        assertThat(contentType)
                .as("Prometheus scrape endpoint must declare exposition format version=0.0.4")
                .contains("version=0.0.4");

        // Body must contain at least one of the standard Spring Boot baseline
        // meters auto-registered by Micrometer; checking for either keeps the
        // assertion robust across minor Boot version changes.
        String body = response.getBody();
        assertThat(body)
                .as("Prometheus body should expose Spring Boot baseline meters")
                .isNotNull();
        assertThat(body.contains("jvm_memory_used_bytes")
                || body.contains("http_server_requests_seconds_count"))
                .as("expected at least one of jvm_memory_used_bytes / "
                        + "http_server_requests_seconds_count in the scrape body")
                .isTrue();
    }
}
