package com.example.searchengine.web.dashboard;

import com.example.searchengine.domain.content.Content;
import com.example.searchengine.domain.content.ContentRepository;
import com.example.searchengine.domain.content.ContentType;
import com.example.searchengine.infrastructure.persistence.ContentJpaRepository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.boot.test.context.SpringBootTest.WebEnvironment.RANDOM_PORT;

/**
 * Integration test for the {@code GET /dashboard} endpoint.
 *
 * <p>Validates Requirements 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8.</p>
 *
 * <p>Boots the full Spring Boot context with a randomly-bound port and a real
 * PostgreSQL 16 instance via Testcontainers. Fixtures are seeded directly
 * through the JPA repository so the rendered HTML can be diffed against a
 * known dataset. The Thymeleaf-rendered response is parsed with simple,
 * resilient string assertions (no third-party HTML library required).</p>
 *
 * <p>The Spring context is configured via {@link DynamicPropertySource} to:
 * <ul>
 *   <li>point the datasource at the running PostgreSQL container,</li>
 *   <li>satisfy the required configuration properties enforced by
 *       {@code ConfigValidator} (provider base URLs are stubbed),</li>
 *   <li>disable the background sync scheduler so tests run deterministically,</li>
 *   <li>disable the rate limiter (irrelevant for {@code /dashboard}, but keeps
 *       the boot path lightweight),</li>
 *   <li>disable search caching so each request hits the database directly.</li>
 * </ul>
 * </p>
 */
@SpringBootTest(webEnvironment = RANDOM_PORT)
@Testcontainers
class DashboardControllerIT {

    @Container
    static final PostgreSQLContainer<?> POSTGRES =
            new PostgreSQLContainer<>("postgres:16")
                    .withDatabaseName("searchengine_test")
                    .withUsername("test")
                    .withPassword("test");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
        // Stub provider base-urls so config validation passes; no provider HTTP
        // traffic is generated by /dashboard.
        registry.add("providers.json.base-url", () -> "http://localhost:0/json");
        registry.add("providers.xml.base-url", () -> "http://localhost:0/xml");
        // Disable scheduled sync so the aggregator never tries to reach the
        // stubbed providers during the test run.
        registry.add("aggregator.sync.enabled", () -> "false");
        // Disable rate limiting (path-irrelevant for /dashboard but keeps the
        // boot path simple — no Redis dependency for buckets either).
        registry.add("ratelimit.enabled", () -> "false");
        // Disable Redis-backed caching; @Cacheable becomes a no-op via
        // NoOpCacheManager so the suite has no Redis dependency.
        registry.add("cache.search.enabled", () -> "false");
    }

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    private ContentJpaRepository contentJpaRepository;

    @Autowired
    private ContentRepository contentRepository;

    @BeforeEach
    void cleanDatabase() {
        contentJpaRepository.deleteAll();
    }

    // ---------------------------------------------------------------------
    // REQ 10.1, 10.2, 10.3 — default ordering, columns, 20-row limit
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard renders Title|Type|Score table ordered by final_score DESC, id ASC, limited to 20")
    void defaultDashboardRendersOrderedTopTwentyTable() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getHeaders().getContentType())
                .matches(ct -> ct != null && ct.includes(MediaType.TEXT_HTML));

        String body = response.getBody();
        assertThat(body).isNotNull();

        // REQ 10.2: exactly the three columns Title | Type | Score
        assertThat(body)
                .contains("<th scope=\"col\">Title</th>")
                .contains("<th scope=\"col\">Type</th>")
                .contains("<th scope=\"col\">Score</th>");

        // REQ 10.3: top 20 rows present (Title-01..Title-20); rows 21-22 absent.
        for (int i = 1; i <= 20; i++) {
            String title = String.format("Title-%02d", i);
            assertThat(body).as("row %d should be rendered", i).contains(title);
        }
        assertThat(body)
                .doesNotContain("Title-21")
                .doesNotContain("Title-22");

        // REQ 10.3: order is final_score DESC; rows 01 and 02 share final_score
        // = 100.0 so the id-ASC tie-break must place Title-01 above Title-02.
        // After the tie, the remaining rows must appear in numeric order
        // because their final_scores are strictly decreasing.
        int previous = -1;
        for (int i = 1; i <= 20; i++) {
            String title = String.format("Title-%02d", i);
            int idx = body.indexOf(title);
            assertThat(idx).as("Title-%02d must appear in the body", i).isPositive();
            assertThat(idx)
                    .as("Title-%02d must come after Title-%02d", i, i - 1)
                    .isGreaterThan(previous);
            previous = idx;
        }

        // No "ignored" notice on a clean default request (REQ 10.5/10.7 negative case).
        assertThat(body).doesNotContain("data-testid=\"ignored-notice\"");
        assertThat(body).doesNotContain("data-testid=\"empty-message\"");
    }

    // ---------------------------------------------------------------------
    // REQ 10.6 — type=video filter
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard?type=video shows only video rows")
    void typeVideoFilterShowsOnlyVideoRows() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?type=video");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // The fixture seeds rows 1..15 as VIDEO and 16..22 as TEXT. After
        // filtering by type=video, the dashboard must include every video
        // title (15 rows < 20-row limit) and no text titles.
        for (int i = 1; i <= 15; i++) {
            assertThat(body).contains(String.format("Title-%02d", i));
        }
        for (int i = 16; i <= 22; i++) {
            assertThat(body)
                    .as("text title %d must be filtered out", i)
                    .doesNotContain(String.format("Title-%02d", i));
        }

        // No ignored-notice on a valid type value.
        assertThat(body).doesNotContain("data-testid=\"ignored-notice\"");
    }

    // ---------------------------------------------------------------------
    // REQ 10.4 — sort=popularity changes the ordering
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard?sort=popularity orders rows by popularity_score DESC")
    void sortPopularityChangesOrdering() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?sort=popularity");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // popularity_score is set so that higher row numbers have higher
        // popularity. The top 20 by popularity DESC are rows 22 down to 3.
        // Rows 1 and 2 (popularity 1 and 2) must be excluded.
        assertThat(body)
                .doesNotContain("Title-01")
                .doesNotContain("Title-02");
        for (int i = 3; i <= 22; i++) {
            assertThat(body).contains(String.format("Title-%02d", i));
        }

        // Ordering: Title-22 first, Title-21 second, ..., Title-03 last.
        int previous = -1;
        for (int i = 22; i >= 3; i--) {
            String title = String.format("Title-%02d", i);
            int idx = body.indexOf(title);
            assertThat(idx).as("Title-%02d must appear", i).isPositive();
            assertThat(idx)
                    .as("Title-%02d (popularity=%d) must come after the previous higher-popularity title", i, i)
                    .isGreaterThan(previous);
            previous = idx;
        }

        // No ignored-notice for a valid sort value.
        assertThat(body).doesNotContain("data-testid=\"ignored-notice\"");
    }

    // ---------------------------------------------------------------------
    // REQ 10.5 — invalid sort produces default ordering plus ignored notice
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard?sort=invalid renders default ordering and an 'ignored' notice")
    void invalidSortRendersDefaultOrderingAndNotice() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?sort=invalid");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // REQ 10.5: visible "ignored" notice is rendered and names the
        // invalid sort value the user provided.
        assertThat(body)
                .contains("data-testid=\"ignored-notice\"")
                .containsIgnoringCase("ignored")
                .contains("sort")
                .contains("invalid");

        // Default ordering is final_score DESC: top 20 rows are 1..20 in order.
        for (int i = 1; i <= 20; i++) {
            assertThat(body).contains(String.format("Title-%02d", i));
        }
        assertThat(body)
                .doesNotContain("Title-21")
                .doesNotContain("Title-22");

        int previous = -1;
        for (int i = 1; i <= 20; i++) {
            int idx = body.indexOf(String.format("Title-%02d", i));
            assertThat(idx).isPositive();
            assertThat(idx).isGreaterThan(previous);
            previous = idx;
        }
    }

    // ---------------------------------------------------------------------
    // REQ 10.7 — invalid type ignores the filter AND surfaces a visible notice
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard?type=invalid ignores the filter and surfaces a visible 'ignored' notice")
    void invalidTypeIgnoresFilterAndRendersNotice() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?type=invalid");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // REQ 10.7: visible "ignored" notice is rendered and names the
        // invalid type value the user provided.
        assertThat(body)
                .contains("data-testid=\"ignored-notice\"")
                .containsIgnoringCase("ignored")
                .contains("type")
                .contains("invalid");

        // REQ 10.7: filter is NOT applied — both VIDEO (rows 1..15) and TEXT
        // (rows 16..22) titles must be present in the rendered table because
        // the dashboard falls back to "no filter" with default ordering. The
        // 20-row cap means rows 1..20 (final_score DESC) are rendered.
        for (int i = 1; i <= 20; i++) {
            assertThat(body).contains(String.format("Title-%02d", i));
        }
        // Rows 16..20 are TEXT; their presence proves the type filter is
        // truly ignored rather than silently applied.
        assertThat(body)
                .contains("Title-16")
                .contains("Title-17")
                .contains("Title-18")
                .contains("Title-19")
                .contains("Title-20");

        // Default ordering remains final_score DESC: rows 21 and 22 fall
        // outside the 20-row cap.
        assertThat(body)
                .doesNotContain("Title-21")
                .doesNotContain("Title-22");
    }

    // ---------------------------------------------------------------------
    // REQ 10.1 — performance: respond within 2 seconds for a 1000-row fixture
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard responds within 2 seconds for a 1000-row fixture (REQ 10.1)")
    void respondsWithinTwoSecondsForLargeFixture() {
        seedLargeFixture(1000);

        long startNanos = System.nanoTime();
        ResponseEntity<String> response = getDashboard("/dashboard");
        Duration elapsed = Duration.ofNanos(System.nanoTime() - startNanos);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getHeaders().getContentType())
                .matches(ct -> ct != null && ct.includes(MediaType.TEXT_HTML));
        // REQ 10.1: 2 seconds for result sets of up to 1000 rows.
        assertThat(elapsed)
                .as("Dashboard must render within 2 seconds for a 1000-row fixture (actual: %s)", elapsed)
                .isLessThanOrEqualTo(Duration.ofSeconds(2));

        String body = response.getBody();
        assertThat(body).isNotNull();
        // Sanity: the rendered table holds the 20-row default cap. The first
        // 20 rows (BIG-0001..BIG-0020) have the highest final_score values.
        for (int i = 1; i <= 20; i++) {
            assertThat(body).contains(String.format("BIG-%04d", i));
        }
    }

    // ---------------------------------------------------------------------
    // REQ 10.8 — empty result set renders the empty-state message
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard with no matching rows renders the empty-state message")
    void emptyResultSetRendersEmptyStateMessage() {
        // Database was cleared by @BeforeEach; seed nothing.

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // REQ 10.8: empty-state message is visible to the user.
        assertThat(body)
                .contains("data-testid=\"empty-message\"")
                .contains("No content items are available.");

        // REQ 10.2: column headers must remain rendered even when the table
        // contains no data rows.
        assertThat(body)
                .contains("<th scope=\"col\">Title</th>")
                .contains("<th scope=\"col\">Type</th>")
                .contains("<th scope=\"col\">Score</th>");

        // No fixture titles should be present.
        assertThat(body).doesNotContain("Title-");
    }

    // =====================================================================
    // dashboard-ux-enhancements — HTML-level assertions (Task 4.1)
    //
    // Validates Requirements 1.6, 3.3, 3.4, 3.5, 4.1, 5.1, 5.2, 5.3, 6.5,
    // 6.6, 7.1, 7.2, 7.3, 7.4, 8.1, 8.2, 8.3, 9.3, 9.4, 9.5, 10.4, 11.2,
    // 11.3, 11.4.
    // =====================================================================

    // ---------------------------------------------------------------------
    // REQ 3.3, 11.2 — sort <select> renders the active option as `selected`
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard?sort=v marks the matching <option> with the selected attribute (REQ 3.3, 11.2)")
    void sortSelectMarksActiveOptionAsSelected() {
        seedFixture();

        for (String v : List.of("score", "popularity", "relevance")) {
            ResponseEntity<String> response = getDashboard("/dashboard?sort=" + v);

            assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
            String body = response.getBody();
            assertThat(body).isNotNull();
            assertThat(body)
                    .as("sort=%s should render <option value=\"%s\" ... selected ...>", v, v)
                    .containsPattern("<option value=\"" + v + "\"[^>]*selected[^>]*>");
        }
    }

    // ---------------------------------------------------------------------
    // REQ 3.4 — type <select> renders the active option as `selected`
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("GET /dashboard?type=v marks the matching <option> with the selected attribute (REQ 3.4)")
    void typeSelectMarksActiveOptionAsSelected() {
        seedFixture();

        for (String v : List.of("text", "video")) {
            ResponseEntity<String> response = getDashboard("/dashboard?type=" + v);

            assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
            String body = response.getBody();
            assertThat(body).isNotNull();
            assertThat(body)
                    .as("type=%s should render <option value=\"%s\" ... selected ...>", v, v)
                    .containsPattern("<option value=\"" + v + "\"[^>]*selected[^>]*>");
        }
    }

    @Test
    @DisplayName("GET /dashboard with no ?type marks the All <option> with the selected attribute (REQ 3.4)")
    void typeSelectMarksAllOptionAsSelectedWhenNoFilter() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();
        assertThat(body)
                .as("no-type request must mark <option value=\"\">All</option> as selected")
                .containsPattern("<option value=\"\"[^>]*selected[^>]*>All</option>");
    }

    // ---------------------------------------------------------------------
    // REQ 7.1, 7.2, 7.4, 11.3 — result-count summary contains row count + sort
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Result-count summary contains the rendered row count and the active sort (REQ 7.1, 7.2, 11.3)")
    void resultCountSummaryContainsRowCountAndActiveSort() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        assertThat(body).contains("data-testid=\"result-count\"");

        // The summary mixes literal text with <span> elements; flatten by
        // stripping tags and collapsing whitespace before checking the text.
        String flat = flattenText(body);
        assertThat(flat)
                .as("summary should report 'Showing 20' against the 22-row fixture (capped to DEFAULT_LIMIT=20)")
                .contains("Showing 20")
                .as("summary should report the active sort")
                .contains("sorted by score");
    }

    @Test
    @DisplayName("Result-count summary on an empty fixture renders 'Showing 0 ... sorted by score' (REQ 7.4)")
    void resultCountSummaryOnEmptyFixture() {
        // @BeforeEach already cleared the database; intentionally seed nothing.

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        assertThat(body).contains("data-testid=\"result-count\"");

        String flat = flattenText(body);
        assertThat(flat).contains("Showing 0");
        assertThat(flat).contains("sorted by score");
    }

    // ---------------------------------------------------------------------
    // REQ 7.3 — result-count summary includes the active type when set
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Result-count summary includes the active type word when ?type=text (REQ 7.3)")
    void resultCountSummaryIncludesActiveTypeWhenSet() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?type=text");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        String flat = flattenText(body);
        assertThat(flat).contains("Showing");
        assertThat(flat).contains("text results sorted by score");
    }

    // ---------------------------------------------------------------------
    // REQ 1.6, 11.4 — Score header link href (with and without type filter)
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Score header link href is /dashboard?sort=score with no type filter (REQ 1.6, 11.4)")
    void scoreHeaderLinkHrefWithoutTypeFilter() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // The closing quote pins the URL — guards against accidentally
        // matching `/dashboard?sort=score&amp;type=...` here.
        assertThat(body).contains("<a href=\"/dashboard?sort=score\"");
    }

    @Test
    @DisplayName("Score header link href is /dashboard?sort=score&amp;type=text with ?type=text (REQ 1.6)")
    void scoreHeaderLinkHrefWithTypeText() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?type=text");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // Thymeleaf HTML-escapes the ampersand inside attribute values.
        assertThat(body).contains("/dashboard?sort=score&amp;type=text");
    }

    // ---------------------------------------------------------------------
    // REQ 3.5 — Active-sort indicator on the Score column header
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Score <th> carries 'active-sort' class and a ▼ glyph when sort=score (REQ 3.5)")
    void scoreHeaderHasActiveSortIndicatorWhenSortIsScore() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?sort=score");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // The Score header is the only <th> with class score-col; classappend
        // adds " active-sort" so the rendered class attribute is exactly
        // "score-col active-sort".
        assertThat(body)
                .as("Score <th> must carry both 'score-col' and 'active-sort' CSS classes")
                .contains("class=\"score-col active-sort\"");
        assertThat(body)
                .as("Active-sort indicator must include a ▼ glyph")
                .contains("▼");
    }

    @Test
    @DisplayName("Score <th> does NOT carry 'active-sort' class when sort=popularity (REQ 3.5)")
    void scoreHeaderHasNoActiveSortClassWhenSortIsNotScore() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard?sort=popularity");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // The token "active-sort" still appears in the inline <style> block
        // (`th.active-sort a { ... }`), so the negative assertion has to be
        // scoped to the class-attribute combination — when sort != score the
        // Score header's class attribute is just "score-col".
        assertThat(body)
                .as("Score <th> class must remain 'score-col' alone when sort != score")
                .doesNotContain("score-col active-sort");
    }

    // ---------------------------------------------------------------------
    // REQ 5.1, 5.2, 5.3 — Type badges render with correct CSS classes
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Body contains type-badge--text and type-badge--video CSS classes against the mixed-type fixture (REQ 5.1–5.3)")
    void typeBadgesRenderWithCorrectCssClasses() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        assertThat(body)
                .contains("class=\"type-badge type-badge--text\"")
                .contains("class=\"type-badge type-badge--video\"");
    }

    // ---------------------------------------------------------------------
    // REQ 4.1 — score formatting (regression guard)
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Score column renders one decimal place (100.0) and never two (100.00) (REQ 4.1)")
    void scoreFormattingUsesOneDecimal() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        // Rows 1 and 2 in the fixture share final_score = 100.0; the new
        // template formats with #numbers.formatDecimal(score, 1, 1) so the
        // rendered text is "100.0" — never "100.00".
        assertThat(body).contains("100.0");
        assertThat(body).doesNotContain("100.00");
    }

    // ---------------------------------------------------------------------
    // REQ 8.1, 8.2, 8.3 — viewport meta + responsive media query
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Body contains viewport meta tag and the @media (max-width: 600px) rule (REQ 8.1, 8.2, 8.3)")
    void bodyContainsViewportMetaAndMediaQuery() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        assertThat(body)
                .contains("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
                .contains("@media (max-width: 600px)");
    }

    // ---------------------------------------------------------------------
    // REQ 9.4, 9.5, 10.4 — no client-side script, no pagination, no search box
    // ---------------------------------------------------------------------

    @Test
    @DisplayName("Body contains no <script>, no <input>, no name=\"page\" and no name=\"q\" (REQ 9.4, 9.5, 10.4)")
    void bodyHasNoScriptOrPaginationOrSearchBox() {
        seedFixture();

        ResponseEntity<String> response = getDashboard("/dashboard");

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String body = response.getBody();
        assertThat(body).isNotNull();

        assertThat(body)
                .as("dashboard must remain 100% server-rendered, no <script> tags")
                .doesNotContain("<script");
        assertThat(body)
                .as("dashboard must not render any <input> element (no search box, no hidden inputs)")
                .doesNotContain("<input");
        assertThat(body)
                .as("dashboard must not introduce pagination controls in this feature")
                .doesNotContain("name=\"page\"");
        assertThat(body)
                .as("dashboard must not introduce a free-text search box in this feature")
                .doesNotContain("name=\"q\"");
    }

    // ---------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------

    private ResponseEntity<String> getDashboard(String path) {
        return restTemplate.getForEntity("http://localhost:" + port + path, String.class);
    }

    /**
     * Flattens an HTML fragment by stripping every tag and collapsing all
     * whitespace runs to a single space. This is enough for assertions on
     * visible textual content (e.g. {@code "Showing 20 results sorted by score"})
     * that would otherwise be split across nested {@code <span>} elements and
     * Thymeleaf-preserved newlines in the source template.
     */
    private static String flattenText(String html) {
        String noTags = html.replaceAll("<[^>]+>", " ");
        return noTags.replaceAll("\\s+", " ").trim();
    }

    /**
     * Seeds 22 rows with predictable, deterministic scores and stable UUIDs.
     *
     * <p>Layout:
     * <ul>
     *   <li>Rows 1..15: type {@link ContentType#VIDEO}</li>
     *   <li>Rows 16..22: type {@link ContentType#TEXT}</li>
     *   <li>Rows 1 and 2 share {@code final_score = 100.0} so the id-ASC
     *       tie-break can be observed (row 1's UUID is lexicographically
     *       smaller than row 2's UUID — see {@link #uuidWithSuffix(int)}).</li>
     *   <li>Rows 3..22 have strictly-decreasing {@code final_score}
     *       (99.0, 98.0, ..., 80.0).</li>
     *   <li>{@code popularity_score} is set to {@code i} so the ordering by
     *       popularity is the reverse of the ordering by final_score.</li>
     * </ul>
     */
    private void seedFixture() {
        Instant publishedAt = Instant.parse("2024-08-01T12:00:00Z");

        for (int i = 1; i <= 22; i++) {
            // final_score: rows 1 and 2 tie at 100.0; the rest decrease by 1.
            double finalScore = (i <= 2) ? 100.0 : (102.0 - i);
            // popularity_score: monotonically increases with i so the
            // popularity ordering is the reverse of the score ordering.
            double popularityScore = (double) i;

            Content content = new Content(
                    uuidWithSuffix(i),
                    "test-provider",
                    "ext-" + i,
                    String.format("Title-%02d", i),
                    "description for row " + i,
                    i <= 15 ? ContentType.VIDEO : ContentType.TEXT,
                    100L,
                    10L,
                    5,
                    2L,
                    null,
                    List.of(),
                    publishedAt,
                    finalScore,
                    popularityScore,
                    0.0,
                    null,  // createdAt — managed by the database
                    null   // updatedAt — managed by the database
            );
            contentRepository.upsert(content);
        }
    }

    /**
     * Seeds {@code n} rows with deterministic, strictly-decreasing
     * {@code final_score} values so the dashboard ordering for the top 20
     * is fully predictable. Used by the REQ 10.1 performance scenario.
     *
     * <p>Rows alternate {@code VIDEO} and {@code TEXT} types so the
     * dashboard's mixed-type rendering path is exercised. UUIDs follow the
     * same {@link #uuidWithSuffix(int)} convention.</p>
     */
    private void seedLargeFixture(int n) {
        Instant publishedAt = Instant.parse("2024-08-01T12:00:00Z");

        for (int i = 1; i <= n; i++) {
            Content content = new Content(
                    uuidWithSuffix(i),
                    "test-provider",
                    "big-" + i,
                    String.format("BIG-%04d", i),
                    "row " + i,
                    (i % 2 == 0) ? ContentType.VIDEO : ContentType.TEXT,
                    100L,
                    10L,
                    5,
                    2L,
                    null,
                    List.of(),
                    publishedAt,
                    // Strictly-decreasing finalScore so row 1 ranks highest
                    // and row n ranks last.
                    (double) (n - i + 1),
                    (double) i,
                    0.0,
                    null,
                    null
            );
            contentRepository.upsert(content);
        }
    }

    /**
     * Returns a deterministic {@link UUID} of the form
     * {@code 00000000-0000-0000-0000-XXXXXXXXXXXX} where the trailing 12 hex
     * digits encode {@code n}. This guarantees a stable lexicographic /
     * numeric ordering by {@code n}, which is what the {@code id ASC}
     * tie-break observed by the dashboard relies on.
     */
    private static UUID uuidWithSuffix(int n) {
        return UUID.fromString(String.format("00000000-0000-0000-0000-%012d", n));
    }
}
